# 代码输出题

## 1.promise

### （1）事件循环模型

```
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
const promise2 = promise1.then(() => {
  throw new Error('error!!!')
})
console.log('promise1', promise1)
console.log('promise2', promise2)
setTimeout(() => {
  console.log('promise1', promise1)
  console.log('promise2', promise2)
}, 2000)

//输出结果
promise1 Promise {<pending>}
promise2 Promise {<pending>}

Uncaught (in promise) Error: error!!!
promise1 Promise {<fulfilled>: "success"}
promise2 Promise {<rejected>: Error: error!!}

```

### （2）值穿透

```
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)

//输出结果
1
```

### （3）错误处理

```
Promise.reject('err!!!')
  .then((res) => {
    console.log('success', res)
  }, (err) => {
    console.log('error', err)
  }).catch(err => {
    console.log('catch', err)
  })

//输出结果
error err!!!

以上是使用reject修改状态，所以会被then的第二个参数回调捕捉到错误，并进行处理
以下是throw错误，然后被catch捕捉
Promise.resolve()
  .then(function success (res) {
    throw new Error('error!!!')
  }, function fail1 (err) {
    console.log('fail1', err)
  }).catch(function fail2 (err) {
    console.log('fail2', err)
  })

```

### （4）综合题

```
//事件循环
setTimeout(function () {
  console.log(1);
}, 100);

new Promise(function (resolve) {
  console.log(2);
  resolve();
  console.log(3);
}).then(function () {
  console.log(4);
  new Promise((resove, reject) => {
    console.log(5);
    setTimeout(() =>  {
      console.log(6);
    }, 10);
  })
});
console.log(7);
console.log(8);

//输出结果
2
3
7
8
4
5
6
1
```

```
//链式调用
Promise.resolve().then(() => {
    console.log('1');
    throw 'Error';
}).then(() => {
    console.log('2');
}).catch(() => {
    console.log('3');
    throw 'Error';
}).then(() => {
    console.log('4');
}).catch(() => {
    console.log('5');
}).then(() => {
    console.log('6');
});

1 
3 
5 
6
```

### （5）总结

```
promise的代码输出题目的主要考点在于两个，分别是事件循环与链式调用
其中事件循环值得注意的是promise.then的回调执行依赖于promise状态的改变，如果没有改变那么就会暂时不被处理
然后链式调用值得注意的是reject会被then的第二个参数捕捉到，throw会被catch捕捉到，还有then的接收值期望是函数，否则会出现值穿透现象
如果要整理一个promise的专题，那么应该分为：
1.基础知识(三个状态 then回调 catch finally)
2.promise方法 all race allSettle?
3.代码输出 事件循环 链式调用 
4.手撕promise
```

